// Mock data
const KEY = {
  BOOKS: "books",
  USERS: "users",
  ORDER: "orders",
  ADMINS: "admins",
};

const METHODPAY = {
  OCD: "OCD",
  BANK: "BANK",
  VISA: "VISA",
};

const STATUSORDER = {
  PENDING: "Pending",
  REJECT: "Reject",
  SUBMIT: "Submit",
  COMPLETED: "Completed",
};

let usersData = [
  {
    userId: "U001",
    name: "Huy Hoàng",
    phoneNumber: "0912345678",
    password: "1234567",
    email: "hoang@hmail.com",
    status: true,
    address: "99 An Dương Vương, Phường 16, Quận 8, Hồ Chí Minh",
    createdAt: "2023-05-12",
  },
  {
    userId: "U002",
    name: "Hùng Quân",
    phoneNumber: "0923456789",
    password: "1234567",
    email: "huyquan@gmail.com",
    status: true,
    address: "15 Minh Thảo, Quận 6, Hồ Chí Minh",
    createdAt: "2023-06-24",
  },
  {
    userId: "U003",
    name: "Phương Nam",
    phoneNumber: "0934567890",
    password: "1234567",
    email: "phuongnam@gmail.com",
    status: true,
    address: "19 Võ Nguyên Giáp, Quận 3, Huyện Nhà bè",
    createdAt: "2022-09-17",
  },
  {
    userId: "U004",
    name: "Phương Nguyên",
    phoneNumber: "0945678901",
    password: "1234567",
    email: "nguyen@gmail.com",
    status: true,
    address: "221 Lý Thường Kiệt, Quận 5, Hồ Chí Minh",
    createdAt: "2021-12-30",
  },
  {
    userId: "U005",
    name: "Phan Thành",
    phoneNumber: "0956789012",
    password: "1234567",
    email: "thanhgay@gmail.com",
    status: true,
    address: "21 Điện Biên Phủ, Quận 3, Hồ Chí Minh",
    createdAt: "2022-04-15",
  },
  {
    userId: "U006",
    name: "Nguyễn Hùng",
    phoneNumber: "0967890123 ",
    password: "1234567",
    email: "hung1233@gmail.com",
    status: true,
    address: "16 An Phú, Quận Tân Bình, Hồ Chí Minh",
    createdAt: "2023-02-11",
  },
  {
    userId: "U007",
    name: "Nhất Nguyệt",
    phoneNumber: "111-222-3333",
    password: "1234567",
    email: "nhat11@gmail.com",
    status: true,
    address: "78 Đào Duy Từ, Huyện Hóc Môn, Hồ Chí Minh",
    createdAt: "2023-03-29",
  },
  {
    userId: "U008",
    name: "Nguyễn Long",
    phoneNumber: "0978901234",
    password: "1234567",
    email: "long@gmail.com",
    status: true,
    address: "12 Trường Sa, quận 7, Hồ Chí Minh",
    createdAt: "2021-11-19",
  },
  {
    userId: "U009",
    name: "Thánh Hiếu",
    phoneNumber: "333-444-5555",
    password: "1234567",
    email: "0989012345",
    status: true,
    address: "16 Nguyễn ĐÌnh Chiểu, Quận 4, Hồ Chí Minh",
    createdAt: "2022-08-05",
  },
  {
    userId: "U010",
    name: "Lân Long",
    password: "1234567",
    phoneNumber: "0990123456 ",
    email: "lan@gmail.com",
    status: true,
    address: "16 Phạm Văn Chí, Quận 6, Hồ Chí Minh",
    createdAt: "2023-01-21",
  },
];

let adminsData = [
  {
    adminID: "A001",
    name: "Black Hawk",
    phoneNumber: "0912345678",
    password: "1234567",
    email: "admin@gmail.com",
    address: "99 An Dương Vương, Phường 16, Quận 8, Hồ Chí Minh",
    createdAt: "2023-05-12",
  },
  {
    adminID: "A002",
    name: "Hùng Quân",
    phoneNumber: "0923456789",
    password: "1234567",
    email: "huyquan@gmail.com",
    address: "15 Minh Thảo, Quận 6, Hồ Chí Minh",
    createdAt: "2023-06-24",
  },
];

let ordersData = [
  {
    orderID: "OR01",
    userID: "U004",
    createdAt: "2024-11-04 10:30",
    fromVendor: "Số 01, Hai Bà Trưng, Hà Nội",
    status: STATUSORDER.COMPLETED,
    method: METHODPAY.OCD,
    products: [
      {
        id: "P001",
        quantity: 2,
      },
      {
        id: "P002",
        quantity: 1,
      },
      {
        id: "P003",
        quantity: 1,
      },
    ],
  },
  {
    orderID: "OR02",
    userID: "U001",
    createdAt: "2024-10-04 10:30",
    fromVendor: "Ninh Hòa, Khánh Hòa",
    status: STATUSORDER.SUBMIT,
    method: METHODPAY.BANK,
    products: [
      {
        id: "P003",
        quantity: 2,
      },
      {
        id: "P004",
        quantity: 2,
      },
      {
        id: "P005",
        quantity: 1,
      },
    ],
  },
  {
    orderID: "OR03",
    userID: "U002",
    createdAt: "2024-12-20 10:30",
    fromVendor: "99 An Dương Vương, Phường 16, Quận 8, HCM",
    status: STATUSORDER.REJECT,
    method: METHODPAY.OCD,
    products: [
      {
        id: "P010",
        quantity: 4,
      },
      {
        id: "P001",
        quantity: 2,
      },
    ],
  },
  {
    orderID: "OR04",
    userID: "U006",
    createdAt: "2024-02-10 10:30",
    fromVendor: "21 Lý Thường Kiệt, Quận 6, Hồ Chí Minh",
    status: STATUSORDER.PENDING,
    method: METHODPAY.OCD,
    products: [
      {
        id: "P006",
        quantity: 2,
      },
    ],
  },
  {
    orderID: "OR05",
    userID: "U010",
    createdAt: "2024-11-21 10:30",
    fromVendor: "61 Bình Đông, Quận 5, Hồ Chí Minh ",
    status: STATUSORDER.PENDING,
    method: METHODPAY.OCD,
    products: [
      {
        id: "P011",
        quantity: 2,
      },
      {
        id: "P006",
        quantity: 1,
      },
    ],
  },
  {
    orderID: "OR06",
    userID: "U001",
    createdAt: "2024-10-10 10:30",
    fromVendor: "18 Gia Phú, Quận 5, Hồ Chí Minh",
    status: STATUSORDER.COMPLETED,
    method: METHODPAY.VISA,
    products: [
      {
        id: "P001",
        quantity: 1,
      },
      {
        id: "P002",
        quantity: 3,
      },
    ],
  },
  {
    orderID: "OR07",
    userID: "U005",
    createdAt: "2024-11-01 10:30",
    fromVendor: "12 Phạm Văn Chí, Quận 6, Hồ Chí Minh",
    status: STATUSORDER.SUBMIT,
    method: METHODPAY.OCD,
    products: [
      {
        id: "P003",
        quantity: 3,
      },
      {
        id: "P006",
        quantity: 2,
      },
      {
        id: "P005",
        quantity: 1,
      },
    ],
  },
  {
    orderID: "OR08",
    userID: "U005",
    createdAt: "2024-09-14 10:30",
    fromVendor: "16 Hàng Mã, Hà Nội",
    status: STATUSORDER.COMPLETED,
    method: METHODPAY.OCD,
    products: [
      {
        id: "P006",
        quantity: 2,
      },
      {
        id: "P004",
        quantity: 2,
      },
      {
        id: "P005",
        quantity: 1,
      },
    ],
  },
  {
    orderID: "OR09",
    userID: "U004",
    createdAt: "2024-07-04 10:30",
    fromVendor: "04 Trần Hưng Đạo, Quận Hoàn Kiếm, Hà Nội",
    status: STATUSORDER.COMPLETED,
    method: METHODPAY.BANK,
    products: [
      {
        id: "P002",
        quantity: 2,
      },
      {
        id: "P005",
        quantity: 2,
      },
    ],
  },
  {
    orderID: "OR10",
    userID: "U002",
    createdAt: "2024-08-04 10:30",
    fromVendor: "50 Điện Biên Phủ, Quận 3, Hồ Chí Minh",
    status: STATUSORDER.SUBMIT,
    method: STATUSORDER.BANK,
    products: [
      {
        id: "P002",
        quantity: 4,
      },
    ],
  },
  {
    orderID: "OR11",
    userID: "U006",
    createdAt: "2024-11-04 10:30",
    fromVendor: "06 Nguyễn Đình Chiểu, Quận 1, Hồ Chí Minh",
    status: STATUSORDER.COMPLETED,
    method: METHODPAY.OCD,
    products: [
      {
        id: "P004",
        quantity: 2,
      },
      {
        id: "P008",
        quantity: 3,
      },
    ],
  },
  {
    orderID: "OR12",
    userID: "U008",
    createdAt: "2024-09-08 10:30",
    fromVendor: "221 Cổ Nhếu, Quận Từ Liêm, Hà Nội",
    status: STATUSORDER.COMPLETED,
    method: METHODPAY.BANK,
    products: [
      {
        id: "P007",
        quantity: 1,
      },
      {
        id: "P012",
        quantity: 2,
      },
      {
        id: "P011",
        quantity: 1,
      },
      {
        id: "P015",
        quantity: 5,
      },
    ],
  },
  {
    orderID: "OR13",
    userID: "U009",
    createdAt: "2024-07-04 10:30",
    fromVendor: "20 Hai Bà Trưng, Ba Đình, Hà Nội",
    status: STATUSORDER.COMPLETED,
    method: METHODPAY.OCD,
    products: [
      {
        id: "P001",
        quantity: 3,
      },
    ],
  },
  {
    orderID: "OR14",
    userID: "U006",
    createdAt: "2024-11-12 10:30",
    fromVendor: "220 An Dương Vương, Phường 8, Quận 5, Hồ Chí Minh",
    status: STATUSORDER.PENDING,
    method: METHODPAY.BANK,
    products: [
      {
        id: "P002",
        quantity: 3,
      },
      {
        id: "P004",
        quantity: 3,
      },
    ],
  },
  {
    orderID: "OR15",
    userID: "U003",
    createdAt: "2024-06-06 10:30",
    fromVendor: "10 Võ Văn Kiệt, Phường 6, Quận 5, Hồ Chí Minh",
    status: STATUSORDER.COMPLETED,
    method: METHODPAY.OCD,
    products: [
      {
        id: "P005",
        quantity: 1,
      },
      {
        id: "P004",
        quantity: 2,
      },
      {
        id: "P010",
        quantity: 5,
      },
    ],
  },
  {
    orderID: "OR16",
    userID: "U005",
    createdAt: "2024-11-21 10:30",
    fromVendor: "16 Nam Từ Liêm, Hà Nội",
    status: STATUSORDER.COMPLETED,
    method: METHODPAY.OCD,
    products: [
      {
        id: "P001",
        quantity: 2,
      },
      {
        id: "P004",
        quantity: 2,
      },
      {
        id: "P005",
        quantity: 3,
      },
    ],
  },
];

let booksData = [
  {
    img: "https://www.dbooks.org/img/books/1098127463s.jpg",
    productID: "P001",
    title: "Bảo mật dưới dạng Mã",
    price: 450000,
    language: "English",
    tags: ["Security", "DevOps"],
    author: "John Doe",
    description:
      "Hướng dẫn toàn diện về việc triển khai bảo mật dưới dạng mã trong quy trình CI/CD của bạn.",
    pages: 250,
    subject: "Hacking",
    publicationDate: "2023-10-01",
    genre: "Technical",
    createdAt: "2024-11-04",
    inStock: 10,
    ratting: 4.8,
    numberOfsale: 10,
  },
  {
    img: "https://www.dbooks.org/img/books/164200233Xs.jpg",
    productID: "P002",
    title: "ASP.NET Core 6 Ngắn Gọn",
    price: 300000,
    language: "English",
    tags: ["ASP.NET", "Web Development"],
    author: "Jane Smith",
    description:
      "Hướng dẫn ngắn gọn về cách phát triển ứng dụng web bằng ASP.NET Core 6.",
    pages: 150,
    subject: "Hacking",
    publicationDate: "2022-08-15",
    genre: "Technical",
    createdAt: "2024-11-04",
    inStock: 10,
    ratting: 4.8,
    numberOfsale: 10,
  },
  {
    img: "https://www.dbooks.org/img/books/5709901124s.jpg",
    productID: "P003",
    title: "Xây dựng một máy nghe nhạc Raspberry Pi",
    price: 280000,
    language: "English",
    tags: ["Raspberry Pi", "DIY"],
    author: "Mark Johnson",
    description:
      "Tìm hiểu cách biến Raspberry Pi của bạn thành một trình phát phương tiện mạnh mẽ.",
    pages: 100,
    subject: "Hacking",
    publicationDate: "2022-05-20",
    genre: "Technical",
    createdAt: "2024-11-01",
    inStock: 10,
    ratting: 4.8,
    numberOfsale: 10,
  },
  {
    img: "https://www.dbooks.org/img/books/191204742Xs.jpg",
    productID: "P004",
    title: "Sổ tay Raspberry Pi chính thức năm 2023",
    price: 350000,
    language: "English",
    tags: ["Raspberry Pi", "Guide"],
    author: "Raspberry Pi Foundation",
    description: "Hướng dẫn tối ưu để tận dụng tối đa Raspberry Pi của bạn.",
    pages: 400,
    subject: "Hacking",
    publicationDate: "2023-01-10",
    genre: "Technical",
    createdAt: "2024-11-09",
    inStock: 10,
    ratting: 4.8,
    numberOfsale: 10,
  },
  {
    img: "https://www.dbooks.org/img/books/1642002275s.jpg",
    productID: "P005",
    title: "Dịch vụ Azure Bot Ngắn gọn",
    price: 250000,
    language: "English",
    tags: ["Azure", "Bots"],
    author: "Emily Davis",
    description:
      "A quick introduction to building bots using Azure Bot Service.",
    pages: 120,
    subject: "Hacking",
    publicationDate: "2023-03-01",
    genre: "Technical",
    createdAt: "2024-11-20",
    inStock: 10,
    ratting: 4.8,
    numberOfsale: 10,
  },
  {
    img: "https://www.dbooks.org/img/books/1098111389s.jpg",
    productID: "P006",
    title: "Quản lý dữ liệu gốc đám mây trên Kubernetes",
    price: 400000,
    language: "English",
    tags: ["Kubernetes", "Cloud"],
    author: "David Brown",
    description:
      "Chiến lược quản lý dữ liệu trong các ứng dụng đám mây trên Kubernetes.",
    pages: 300,
    subject: " Hacking",
    publicationDate: "2023-09-01",
    genre: "Technical",
    createdAt: "2024-11-19",
    inStock: 10,
    ratting: 4.8,
    numberOfsale: 10,
  },
  {
    img: "https://www.dbooks.org/img/books/1912047446s.jpg",
    productID: "P007",
    title: "Giới thiệu về lập trình C & GUI",
    price: 320000,
    language: "English",
    tags: ["C", "GUI", "Programming"],
    author: "Sarah White",
    description:
      "A beginner's guide to programming in C and creating graphical user interfaces.",
    pages: 180,
    subject: "Programming",
    publicationDate: "2022-06-30",
    genre: "Technical",
    createdAt: "2024-11-30",
    inStock: 10,
    ratting: 4.8,
    numberOfsale: 10,
  },
  {
    img: "https://www.dbooks.org/img/books/5685527822s.jpg",
    productID: "P008",
    title: "Tạp chí HackSpace: Số 65",
    price: 150000,
    language: "English",
    tags: ["Magazine", "Hacking"],
    author: "Various",
    description:
      "Số mới nhất của Tạp chí HackSpace giới thiệu các dự án và hướng dẫn thú vị.",
    pages: 70,
    subject: "Hacking",
    publicationDate: "2023-11-01",
    genre: "Magazine",
    createdAt: "2024-11-25",
    inStock: 10,
    ratting: 4.8,
    numberOfsale: 10,
  },
  {
    img: "https://www.dbooks.org/img/books/5685535457s.jpg",
    productID: "P009",
    title: "Giới thiệu về phương tiện truyền thông xã hội",
    price: 200000,
    language: "English",
    tags: ["Social Media", "Marketing"],
    author: "Lisa Green",
    description:
      "Giới thiệu về thế giới truyền thông xã hội và tác động của nó đến tiếp thị.",
    pages: 220,
    subject: "Hacking",
    publicationDate: "2023-05-15",
    genre: "Business",
    createdAt: "2024-11-08",
    inStock: 10,
    ratting: 4.8,
    numberOfsale: 10,
  },
  {
    img: "https://www.dbooks.org/img/books/5679752518s.jpg",
    productID: "P010",
    title: "Tạp chí HackSpace: Số 64",
    price: 150000,
    language: "English",
    tags: ["Magazine", "Hacking"],
    author: "Various",
    description:
      "Một số ấn bản thú vị khác của Tạp chí HackSpace với các dự án mới.",
    pages: 72,
    subject: "Hacking",
    publicationDate: "2023-09-01",
    genre: "Magazine",
    createdAt: "2024-11-21",
    inStock: 10,
    ratting: 4.8,
    numberOfsale: 10,
  },
  {
    img: "https://www.dbooks.org/img/books/1642002305s.jpg",
    productID: "P011",
    title: "Svelte Ngắn Gọn",
    price: 280000,
    language: "English",
    tags: ["Svelte", "Web Development"],
    author: "Tom Williams",
    description:
      "Giới thiệu về cách xây dựng ứng dụng web bằng nền tảng Svelte.",
    pages: 140,
    subject: "Hacking",
    publicationDate: "2022-07-01",
    genre: "Technical",
    createdAt: "2024-11-03",
    inStock: 10,
    ratting: 4.8,
    numberOfsale: 10,
  },
  {
    img: "https://www.dbooks.org/img/books/111954601Xs.jpg",
    productID: "P012",
    title: "Blockchain dành cho người mới bắt đầu",
    price: 320000,
    language: "English",
    tags: ["Blockchain", "Finance"],
    author: "P. K. Mishra",
    description:
      "Hướng dẫn thân thiện với người mới bắt đầu để hiểu công nghệ blockchain.",
    pages: 180,
    subject: "Hacking",
    publicationDate: "2021-11-05",
    genre: "Business",
    createdAt: "2024-11-04",
    inStock: 10,
    ratting: 4.8,
    numberOfsale: 10,
  },
  {
    img: "https://www.dbooks.org/img/books/1642002283s.jpg",
    productID: "P013",
    title: "API ASP.NET Core Một Cách Ngắn Gọn",
    price: 300000,
    language: "English",
    tags: ["ASP.NET", "Web Development"],
    author: "Jane Smith",
    description: "Hướng dẫn ngắn gọn về việc xây dựng API với ASP.NET Core.",
    pages: 160,
    subject: "Hacking",
    publicationDate: "2022-09-01",
    genre: "Technical",
    createdAt: "2024-11-04",
    inStock: 10,
    ratting: 4.8,
    numberOfsale: 10,
  },
  {
    img: "https://www.dbooks.org/img/books/1492095176s.jpg",
    productID: "P014",
    title: "Hướng Dẫn Thực Hành Về Di Chuyển Đám Mây",
    price: 370000,
    language: "English",
    tags: ["Cloud", "Migration"],
    author: "Mark Smith",
    description:
      "Chiến lược để di chuyển ứng dụng của bạn lên đám mây một cách hiệu quả.",
    pages: 250,
    subject: "Hacking",
    publicationDate: "2023-02-01",
    genre: "Technical",
    createdAt: "2024-11-04",
    inStock: 10,
    ratting: 4.8,
    numberOfsale: 10,
  },
  {
    img: "https://www.dbooks.org/img/books/5676984863s.jpg",
    productID: "P015",
    title: "Tạp chí HackSpace: Số 63",
    price: 150000,
    language: "English",
    tags: ["Magazine", "Hacking"],
    author: "Various",
    description:
      "Khám phá những mẹo và dự án mới trong số này của Tạp chí HackSpace.",
    pages: 70,
    subject: "Hacking",
    publicationDate: "2023-07-01",
    genre: "Magazine",
    createdAt: "2024-11-04",
    inStock: 10,
    ratting: 4.8,
    numberOfsale: 10,
  },
  {
    img: "https://www.dbooks.org/img/books/1642002267s.jpg",
    productID: "P016",
    title: "Azure Maps Sử Dụng Blazor Một Cách Ngắn Gọn",
    price: 260000,
    language: "English",
    tags: ["Azure", "Blazor"],
    author: "Helen Carter",
    description: "Xây dựng bản đồ tương tác trong Blazor sử dụng Azure Maps.",
    pages: 150,
    subject: "Web Development",
    publicationDate: "2023-05-01",
    genre: "Technical",
    createdAt: "2024-11-04",
    inStock: 10,
    ratting: 4.8,
    numberOfsale: 10,
  },
  {
    img: "https://www.dbooks.org/img/books/1491931663s.jpg",
    productID: "P017",
    title: "C++ Ngày Nay",
    price: 350000,
    language: "English",
    tags: ["C++", "Programming"],
    author: "Sam Lee",
    description: "Hướng dẫn hiện đại về lập trình C++ và các ứng dụng của nó.",
    pages: 280,
    subject: "Programming",
    publicationDate: "2022-03-01",
    genre: "Technical",
    createdAt: "2024-11-04",
    inStock: 10,
    ratting: 4.8,
    numberOfsale: 10,
  },
  {
    img: "https://www.dbooks.org/img/books/5672335136s.jpg",
    productID: "P018",
    title: "Clojure Trong Những Mảnh Nhỏ",
    price: 400000,
    language: "English",
    tags: ["Clojure", "Functional Programming"],
    author: "William Brown",
    description:
      "Một cái nhìn sâu sắc về Clojure và các ứng dụng thực tiễn của nó.",
    pages: 300,
    subject: "Programming",
    publicationDate: "2022-12-01",
    genre: "Technical",
    createdAt: "2024-11-04",
    inStock: 10,
    ratting: 4.8,
    numberOfsale: 10,
  },
  {
    img: "https://www.dbooks.org/img/books/1119824281s.jpg",
    productID: "P019",
    title: "Redis For Dummies",
    price: 320000,
    language: "English",
    tags: ["Redis", "Databases"],
    author: "Jim Green",
    description: "Một giới thiệu dễ hiểu về Redis và các khả năng của nó.",
    pages: 150,
    subject: "Databases",
    publicationDate: "2021-10-01",
    genre: "Technical",
    createdAt: "2024-11-04",
    inStock: 10,
    ratting: 4.8,
    numberOfsale: 10,
  },
  {
    img: "https://www.dbooks.org/img/books/1492038253s.jpg",
    productID: "P020",
    title: "Thiết kế hệ thống hướng sự kiện",
    price: 400000,
    language: "English",
    tags: ["Event-Driven", "Architecture"],
    author: "Nina White",
    description: "Hướng dẫn xây dựng kiến trúc sự kiện mạnh mẽ.",
    pages: 350,
    subject: "Software Architecture",
    publicationDate: "2022-04-01",
    genre: "Technical",
    createdAt: "2024-11-04",
    inStock: 10,
    ratting: 4.8,
    numberOfsale: 10,
  },
  {
    img: "https://www.dbooks.org/img/books/1938616049s.jpg",
    productID: "P021",
    title: "Sổ tay Erlang",
    price: 280000,
    language: "English",
    tags: ["Erlang", "Programming"],
    author: "Alice Black",
    description: "Hướng dẫn hoàn chỉnh về lập trình Erlang.",
    pages: 200,
    subject: "Programming",
    publicationDate: "2021-12-15",
    genre: "Technical",
    createdAt: "2024-11-04",
    inStock: 10,
    ratting: 4.8,
    numberOfsale: 10,
  },
  {
    img: "https://www.dbooks.org/img/books/5671111456s.jpg",
    productID: "P022",
    title: "Tạp chí HackSpace: Số 62",
    price: 150000,
    language: "English",
    tags: ["Magazine", "Hacking"],
    author: "Various",
    description: "Các dự án và hướng dẫn mới nhất từ cộng đồng HackSpace.",
    pages: 75,
    subject: "Hacking",
    publicationDate: "2023-05-01",
    genre: "Magazine",
    createdAt: "2024-11-04",
    inStock: 10,
    ratting: 4.8,
    numberOfsale: 10,
  },
];

function getLocalStorage(key) {
  const data = localStorage.getItem(key);
  return data ? JSON.parse(data) : null;
}

function setLocalStorage(key, value) {
  if (value !== undefined) {
    localStorage.setItem(key, JSON.stringify(value));
  }
}

function initializeLocalStorage(key, defaultData) {
  if (!getLocalStorage(key)) {
    setLocalStorage(key, defaultData);
  }
  return getLocalStorage(key);
}

let books = initializeLocalStorage(KEY.BOOKS, booksData);
let users = initializeLocalStorage(KEY.USERS, usersData);
let orders = initializeLocalStorage(KEY.ORDER, ordersData);
let admins = initializeLocalStorage(KEY.ADMINS, adminsData);
let products = getLocalStorage(KEY.BOOKS);
