// Mock data
let users = [
  {
    userId: "U001",
    name: "Alice Smith",
    phoneNumber: "987-654-3210",
    email: "alice.smith@example.com",
    address: "456 Elm St",
    createdAt: "2023-05-12",
    numberOfOrder: 3,
  },
  {
    userId: "U002",
    name: "Bob Johnson",
    phoneNumber: "321-654-9870",
    email: "bob.johnson@example.com",
    address: "789 Pine St",
    createdAt: "2023-06-24",
    numberOfOrder: 7,
  },
  {
    userId: "U003",
    name: "Clara Liu",
    phoneNumber: "654-321-9876",
    email: "clara.liu@example.com",
    address: "101 Oak St",
    createdAt: "2022-09-17",
    numberOfOrder: 2,
  },
  {
    userId: "U004",
    name: "David Brown",
    phoneNumber: "789-123-4560",
    email: "david.brown@example.com",
    address: "234 Maple St",
    createdAt: "2021-12-30",
    numberOfOrder: 10,
  },
  {
    userId: "U005",
    name: "Emily Davis",
    phoneNumber: "456-789-1234",
    email: "emily.davis@example.com",
    address: "567 Birch St",
    createdAt: "2022-04-15",
    numberOfOrder: 5,
  },
  {
    userId: "U006",
    name: "Frank White",
    phoneNumber: "234-567-8901",
    email: "frank.white@example.com",
    address: "890 Cedar St",
    createdAt: "2023-02-11",
    numberOfOrder: 1,
  },
  {
    userId: "U007",
    name: "Grace Martinez",
    phoneNumber: "111-222-3333",
    email: "grace.martinez@example.com",
    address: "123 Willow St",
    createdAt: "2023-03-29",
    numberOfOrder: 8,
  },
  {
    userId: "U008",
    name: "Henry Walker",
    phoneNumber: "222-333-4444",
    email: "henry.walker@example.com",
    address: "456 Poplar St",
    createdAt: "2021-11-19",
    numberOfOrder: 0,
  },
  {
    userId: "U009",
    name: "Irene Scott",
    phoneNumber: "333-444-5555",
    email: "irene.scott@example.com",
    address: "789 Sycamore St",
    createdAt: "2022-08-05",
    numberOfOrder: 12,
  },
  {
    userId: "U010",
    name: "Jack Lee",
    phoneNumber: "444-555-6666",
    email: "jack.lee@example.com",
    address: "101 Palm St",
    createdAt: "2023-01-21",
    numberOfOrder: 4,
  },
];

let orders = [
  {
    orderID: "U001",
    userID: "U001",
    createdAt: "2024-11-04 10:30",
    fromVendor: "Hà Nội",
    status: "Pending",
    method: "OCD",
    products: [
      {
        id: "P001",
        quantity: 1,
      },
      {
        id: "P002",
        quantity: 1,
      },
      {
        id: "P003",
        quantity: 1,
      },
      {
        id: "P004",
        quantity: 1,
      },
      {
        id: "P005",
        quantity: 1,
      },
    ],
  },
];

let books = [
  {
    img: "https://www.dbooks.org/img/books/1098127463s.jpg",
    productID: "P001",
    title: "Security as Code",
    price: 450000,
    language: "English",
    tags: ["Security", "DevOps"],
    author: "John Doe",
    description:
      "A comprehensive guide to implementing security as code in your CI/CD pipelines.",
    pages: 250,
    subject: "Cybersecurity",
    publicationDate: "2023-10-01",
    genre: "Technical",
    createdAt: "2024-11-01",
    inStock: 10,
    ratting: 4.8,
    numberOfsale: 10,
  },
  {
    img: "https://www.dbooks.org/img/books/164200233Xs.jpg",
    productID: "P002",
    title: "ASP.NET Core 6 Succinctly",
    price: 300000,
    language: "English",
    tags: ["ASP.NET", "Web Development"],
    author: "Jane Smith",
    description:
      "A concise guide to developing web applications using ASP.NET Core 6.",
    pages: 150,
    subject: "Web Development",
    publicationDate: "2022-08-15",
    genre: "Technical",
    createdAt: "2024-11-10",
    inStock: 10,
    ratting: 4.8,
    numberOfsale: 10,
  },
  {
    img: "https://www.dbooks.org/img/books/5709901124s.jpg",
    productID: "P003",
    title: "Build a Raspberry Pi Media Player",
    price: 280000,
    language: "English",
    tags: ["Raspberry Pi", "DIY"],
    author: "Mark Johnson",
    description:
      "Learn how to turn your Raspberry Pi into a powerful media player.",
    pages: 100,
    subject: "DIY Projects",
    publicationDate: "2022-05-20",
    genre: "Technical",
    createdAt: "2024-11-9",
    inStock: 10,
    ratting: 4.8,
    numberOfsale: 10,
  },
  {
    img: "https://www.dbooks.org/img/books/191204742Xs.jpg",
    productID: "P004",
    title: "The Official Raspberry Pi Handbook 2023",
    price: 350000,
    language: "English",
    tags: ["Raspberry Pi", "Guide"],
    author: "Raspberry Pi Foundation",
    description:
      "The ultimate guide to getting the most out of your Raspberry Pi.",
    pages: 400,
    subject: "DIY Projects",
    publicationDate: "2023-01-10",
    genre: "Technical",
    createdAt: "2024-11-30",
    inStock: 10,
    ratting: 4.8,
    numberOfsale: 10,
  },
  {
    img: "https://www.dbooks.org/img/books/1642002275s.jpg",
    productID: "P005",
    title: "Azure Bot Service Succinctly",
    price: 250000,
    language: "English",
    tags: ["Azure", "Bots"],
    author: "Emily Davis",
    description:
      "A quick introduction to building bots using Azure Bot Service.",
    pages: 120,
    subject: "Cloud Computing",
    publicationDate: "2023-03-01",
    genre: "Technical",
    createdAt: "2024-11-20",
    inStock: 10,
    ratting: 4.8,
    numberOfsale: 10,
  },
  {
    img: "https://www.dbooks.org/img/books/1098111389s.jpg",
    productID: "P006",
    title: "Managing Cloud Native Data on Kubernetes",
    price: 400000,
    language: "English",
    tags: ["Kubernetes", "Cloud"],
    author: "David Brown",
    description:
      "Strategies for managing data in cloud-native applications on Kubernetes.",
    pages: 300,
    subject: "Cloud Computing",
    publicationDate: "2023-09-01",
    genre: "Technical",
    createdAt: "2024-11-19",
    inStock: 10,
    ratting: 4.8,
    numberOfsale: 10,
  },
  {
    img: "https://www.dbooks.org/img/books/1912047446s.jpg",
    productID: "P007",
    title: "An Introduction to C & GUI Programming",
    price: 320000,
    language: "English",
    tags: ["C", "GUI", "Programming"],
    author: "Sarah White",
    description:
      "A beginner's guide to programming in C and creating graphical user interfaces.",
    pages: 180,
    subject: "Programming",
    publicationDate: "2022-06-30",
    genre: "Technical",
    createdAt: "2024-11-28",
    inStock: 10,
    ratting: 4.8,
    numberOfsale: 10,
  },
  {
    img: "https://www.dbooks.org/img/books/5685527822s.jpg",
    productID: "P008",
    title: "HackSpace Magazine: Issue 65",
    price: 150000,
    language: "English",
    tags: ["Magazine", "Hacking"],
    author: "Various",
    description:
      "The latest issue of HackSpace Magazine covering exciting projects and tutorials.",
    pages: 70,
    subject: "Hacking",
    publicationDate: "2023-11-01",
    genre: "Magazine",
    createdAt: "2024-11-02",
    inStock: 10,
    ratting: 4.8,
    numberOfsale: 10,
  },
  {
    img: "https://www.dbooks.org/img/books/5685535457s.jpg",
    productID: "P009",
    title: "Intro to Social Media",
    price: 200000,
    language: "English",
    tags: ["Social Media", "Marketing"],
    author: "Lisa Green",
    description:
      "An introduction to the world of social media and its impact on marketing.",
    pages: 220,
    subject: "Marketing",
    publicationDate: "2023-05-15",
    genre: "Business",
    createdAt: "2024-11-04",
    inStock: 10,
    ratting: 4.8,
    numberOfsale: 10,
  },
  {
    img: "https://www.dbooks.org/img/books/5679752518s.jpg",
    productID: "P010",
    title: "HackSpace magazine: Issue 64",
    price: 150000,
    language: "English",
    tags: ["Magazine", "Hacking"],
    author: "Various",
    description:
      "Another exciting issue of HackSpace Magazine with new projects.",
    pages: 72,
    subject: "Hacking",
    publicationDate: "2023-09-01",
    genre: "Magazine",
    createdAt: "2024-11-04",
    inStock: 10,
    ratting: 4.8,
    numberOfsale: 10,
  },
  {
    img: "https://www.dbooks.org/img/books/1642002305s.jpg",
    productID: "P011",
    title: "Svelte Succinctly",
    price: 280000,
    language: "English",
    tags: ["Svelte", "Web Development"],
    author: "Tom Williams",
    description:
      "An introduction to building web applications using the Svelte framework.",
    pages: 140,
    subject: "Web Development",
    publicationDate: "2022-07-01",
    genre: "Technical",
    createdAt: "2024-11-29",
    inStock: 10,
    ratting: 4.8,
    numberOfsale: 10,
  },
  {
    img: "https://www.dbooks.org/img/books/111954601Xs.jpg",
    productID: "P012",
    title: "Blockchain For Dummies",
    price: 320000,
    language: "English",
    tags: ["Blockchain", "Finance"],
    author: "P. K. Mishra",
    description:
      "A beginner-friendly guide to understanding blockchain technology.",
    pages: 180,
    subject: "Finance",
    publicationDate: "2021-11-05",
    genre: "Business",
    createdAt: "2024-11-25",
    inStock: 10,
    ratting: 4.8,
    numberOfsale: 10,
  },
  {
    img: "https://www.dbooks.org/img/books/1642002283s.jpg",
    productID: "P013",
    title: "ASP.NET Core APIs Succinctly",
    price: 300000,
    language: "English",
    tags: ["ASP.NET", "Web Development"],
    author: "Jane Smith",
    description: "A concise guide to building APIs with ASP.NET Core.",
    pages: 160,
    subject: "Web Development",
    publicationDate: "2022-09-01",
    genre: "Technical",
    createdAt: "2024-11-15",
    inStock: 10,
    ratting: 4.8,
    numberOfsale: 10,
  },
  {
    img: "https://www.dbooks.org/img/books/1492095176s.jpg",
    productID: "P014",
    title: "A Practical Guide to Cloud Migration",
    price: 370000,
    language: "English",
    tags: ["Cloud", "Migration"],
    author: "Mark Smith",
    description:
      "Strategies for migrating your applications to the cloud effectively.",
    pages: 250,
    subject: "Cloud Computing",
    publicationDate: "2023-02-01",
    genre: "Technical",
    createdAt: "2024-11-04",
    inStock: 10,
    ratting: 4.8,
    numberOfsale: 10,
  },
  {
    img: "https://www.dbooks.org/img/books/5676984863s.jpg",
    productID: "P015",
    title: "HackSpace Magazine: Issue 63",
    price: 150000,
    language: "English",
    tags: ["Magazine", "Hacking"],
    author: "Various",
    description:
      "Explore new hacks and projects in this issue of HackSpace Magazine.",
    pages: 70,
    subject: "Hacking",
    publicationDate: "2023-07-01",
    genre: "Magazine",
    createdAt: "2024-11-04",
    inStock: 10,
    ratting: 4.8,
    numberOfsale: 10,
  },
  {
    img: "https://www.dbooks.org/img/books/1642002267s.jpg",
    productID: "P016",
    title: "Azure Maps Using Blazor Succinctly",
    price: 260000,
    language: "English",
    tags: ["Azure", "Blazor"],
    author: "Helen Carter",
    description: "Build interactive maps in Blazor using Azure Maps.",
    pages: 150,
    subject: "Web Development",
    publicationDate: "2023-05-01",
    genre: "Technical",
    createdAt: "2024-11-04",
    inStock: 10,
    ratting: 4.8,
    numberOfsale: 10,
  },
  {
    img: "https://www.dbooks.org/img/books/1491931663s.jpg",
    productID: "P017",
    title: "C++ Today",
    price: 350000,
    language: "English",
    tags: ["C++", "Programming"],
    author: "Sam Lee",
    description: "A modern guide to C++ programming and its applications.",
    pages: 280,
    subject: "Programming",
    publicationDate: "2022-03-01",
    genre: "Technical",
    createdAt: "2024-11-04",
    inStock: 10,
    ratting: 4.8,
    numberOfsale: 10,
  },
  {
    img: "https://www.dbooks.org/img/books/5672335136s.jpg",
    productID: "P018",
    title: "Clojure In Small Pieces",
    price: 400000,
    language: "English",
    tags: ["Clojure", "Functional Programming"],
    author: "William Brown",
    description: "A deep dive into Clojure and its practical applications.",
    pages: 300,
    subject: "Programming",
    publicationDate: "2022-12-01",
    genre: "Technical",
    createdAt: "2024-11-04",
    inStock: 10,
    ratting: 4.8,
    numberOfsale: 10,
  },
  {
    img: "https://www.dbooks.org/img/books/1119824281s.jpg",
    productID: "P019",
    title: "Redis For Dummies",
    price: 320000,
    language: "English",
    tags: ["Redis", "Databases"],
    author: "Jim Green",
    description:
      "An easy-to-understand introduction to Redis and its capabilities.",
    pages: 150,
    subject: "Databases",
    publicationDate: "2021-10-01",
    genre: "Technical",
    createdAt: "2024-11-04",
    inStock: 10,
    ratting: 4.8,
    numberOfsale: 10,
  },
  {
    img: "https://www.dbooks.org/img/books/1492038253s.jpg",
    productID: "P020",
    title: "Designing Event-Driven Systems",
    price: 400000,
    language: "English",
    tags: ["Event-Driven", "Architecture"],
    author: "Nina White",
    description: "Guidelines for building robust event-driven architectures.",
    pages: 350,
    subject: "Software Architecture",
    publicationDate: "2022-04-01",
    genre: "Technical",
    createdAt: "2024-11-04",
    inStock: 10,
    ratting: 4.8,
    numberOfsale: 10,
  },
  {
    img: "https://www.dbooks.org/img/books/1938616049s.jpg",
    productID: "P021",
    title: "Erlang Handbook",
    price: 280000,
    language: "English",
    tags: ["Erlang", "Programming"],
    author: "Alice Black",
    description: "A complete guide to Erlang programming.",
    pages: 200,
    subject: "Programming",
    publicationDate: "2021-12-15",
    genre: "Technical",
    createdAt: "2024-11-04",
    inStock: 10,
    ratting: 4.8,
    numberOfsale: 10,
  },
  {
    img: "https://www.dbooks.org/img/books/5671111456s.jpg",
    productID: "P022",
    title: "HackSpace Magazine: Issue 62",
    price: 150000,
    language: "English",
    tags: ["Magazine", "Hacking"],
    author: "Various",
    description:
      "The latest projects and tutorials from the HackSpace community.",
    pages: 75,
    subject: "Hacking",
    publicationDate: "2023-05-01",
    genre: "Magazine",
    createdAt: "2024-11-04",
    inStock: 10,
    ratting: 4.8,
    numberOfsale: 10,
  },
];

let sales = [
  {
    saleId: "S001",
    orderId: "U001",
    userId: "U001",
    productId: "P001",
  },
  {
    saleId: "S002",
    orderId: "U001",
    userId: "U002",
    productId: "P001",
  },
  {
    saleId: "S003",
    orderId: "U001",
    userId: "U001",
    productId: "P003",
  },
  {
    saleId: "S004",
    orderId: "U001",
    userId: "U001",
    productId: "P005",
  },
  {
    saleId: "S005",
    orderId: "U001",
    userId: "U001",
    productId: "P006",
  },
];
